In [1]:
cd

C:\Users\GunjanPandya


In [2]:
pwd

'C:\\Users\\GunjanPandya'

In [3]:
cd C:\\Users\\GunjanPandya\\Downloads

C:\Users\GunjanPandya\Downloads


In [4]:
#Read the data

import numpy as np
import pandas as pd

with open('.\\Clothing_Shoes_and_Jewelry_5.json', 'r') as f:
    data = f.readlines()

# remove the trailing "\n" from each line
data = map(lambda x: x.rstrip(), data)

# each element of 'data' is an individual JSON object.
# i want to convert it into an array of JSON objects
# which, in and of itself, is one large JSON object
# basically... add square brackets to the beginning
# and end, and have all the individual business JSON objects
# separated by a comma
data_json_str = "[" + ','.join(data) + "]"

# now, load it into pandas
data_df = pd.read_json(data_json_str)

In [5]:
data_df.head()

asin helpful  overall  \
0  0000031887  [0, 0]        5   
1  0000031887  [0, 0]        5   
2  0000031887  [0, 0]        5   
3  0000031887  [0, 0]        5   
4  0000031887  [0, 0]        5   

                                          reviewText   reviewTime  \
0  This is a great tutu and at a really great pri...  02 12, 2011   
1  I bought this for my 4 yr old daughter for dan...  01 19, 2013   
2  What can I say... my daughters have it in oran...   01 4, 2013   
3  We bought several tutus at once, and they are ...  04 27, 2014   
4  Thank you Halo Heaven great product for Little...  03 15, 2014   

       reviewerID                 reviewerName                        summary  \
0  A1KLRMWW2FWPL4  Amazon Customer "cameramom"  Great tutu-  not cheaply made   
1  A2G5TCU2WDFZ65              Amazon Customer                    Very Cute!!   
2  A1RLQXYNCMWRWN                       Carola       I have buy more than one   
3   A8U3FAMSJVHS5                      Caromcg               Adorable, Sturdy   
4  A3GEOILWLK86XM                           CJ        Grammy's Angels Love it   

   unixReviewTime  
0      1297468800  
1      1358553600  
2      1357257600  
3      1398556800  
4      1394841600

In [6]:
data_array = np.array(data_df)

In [7]:
data_array

array([['0000031887', [0, 0], 5, ..., 'Amazon Customer "cameramom"',
        'Great tutu-  not cheaply made', 1297468800],
       ['0000031887', [0, 0], 5, ..., 'Amazon Customer', 'Very Cute!!',
        1358553600],
       ['0000031887', [0, 0], 5, ..., 'Carola', 'I have buy more than one',
        1357257600],
       ..., 
       ['B00KKXCJQU', [1, 1], 5, ..., 'Margaret Picky',
        'Convenient, lightweight, and durable', 1402185600],
       ['B00KKXCJQU', [2, 2], 5, ..., 'Noname',
        'Holds Up Well In Real World Test', 1404691200],
       ['B00KKXCJQU', [0, 1], 5, ...,
        'THE-DEADLY-DOG "Living and Loving Life."',
        "Don't Travel? Still Way too Useful for 'Average Joe'", 1403481600]], dtype=object)

In [9]:
rows, row_pos = np.unique(data_array[:, 0], return_inverse=True)
cols, col_pos = np.unique(data_array[:, 1], return_inverse=True)
rows, row_pos = np.unique(data_array[:, 0], return_inverse=True)
cols, col_pos = np.unique(data_array[:, 1], return_inverse=True)
pivot_table = np.zeros((len(rows), len(cols)), dtype=data_array.dtype)
pivot_table[row_pos, col_pos] = data_array[:, 2]

In [10]:
pivot_table

array([[5, 0, 0, ..., 0, 0, 0],
       [4, 5, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [5, 5, 0, ..., 0, 0, 0]], dtype=object)

In [12]:
data_df_slim = data_df[['asin', 'overall', 'reviewerID']]

In [13]:
user_item_mat = data_df_slim.pivot(index='reviewerID', columns = 'asin', values='overall')

In [14]:
user_item_mat.head()

asin                   0000031887  0123456479  1608299953  1617160377  \
reviewerID                                                              
A001114613O3F18Q5NVR6         NaN         NaN         NaN         NaN   
A00146182PNM90WNNAZ5Q         NaN         NaN         NaN         NaN   
A00165422B2GAUE3EL6Z0         NaN         NaN         NaN         NaN   
A00338282E99B8OR2JYTZ         NaN         NaN         NaN         NaN   
A00354001GE099Q1FL0TU         NaN         NaN         NaN         NaN   

asin                   B00001W0KA  B00001WRHJ  B00004SR8W  B00004SR8Z  \
reviewerID                                                              
A001114613O3F18Q5NVR6         NaN         NaN         NaN         NaN   
A00146182PNM90WNNAZ5Q         NaN         NaN         NaN         NaN   
A00165422B2GAUE3EL6Z0         NaN         NaN         NaN         NaN   
A00338282E99B8OR2JYTZ         NaN         NaN         NaN         NaN   
A00354001GE099Q1FL0TU         NaN         NaN         NaN         NaN   

asin                   B00004SR9P  B00004U1J2     ...      B00K0BPFY0  \
reviewerID                                        ...                   
A001114613O3F18Q5NVR6         NaN         NaN     ...             NaN   
A00146182PNM90WNNAZ5Q         NaN         NaN     ...             NaN   
A00165422B2GAUE3EL6Z0         NaN         NaN     ...             NaN   
A00338282E99B8OR2JYTZ         NaN         NaN     ...             NaN   
A00354001GE099Q1FL0TU         NaN         NaN     ...             NaN   

asin                   B00K551QR6  B00K5T4NHC  B00K8J06CK  B00KA2X4QK  \
reviewerID                                                              
A001114613O3F18Q5NVR6         NaN         NaN         NaN         NaN   
A00146182PNM90WNNAZ5Q         NaN         NaN         NaN         NaN   
A00165422B2GAUE3EL6Z0         NaN         NaN         NaN         NaN   
A00338282E99B8OR2JYTZ         NaN         NaN         NaN         NaN   
A00354001GE099Q1FL0TU         NaN         NaN         NaN         NaN   

asin                   B00KA602SY  B00KCWMG5S  B00KF9180W  B00KGCLROK  \
reviewerID                                                              
A001114613O3F18Q5NVR6         NaN         NaN         NaN         NaN   
A00146182PNM90WNNAZ5Q         NaN         NaN         NaN         NaN   
A00165422B2GAUE3EL6Z0         NaN         NaN         NaN         NaN   
A00338282E99B8OR2JYTZ         NaN         NaN         NaN         NaN   
A00354001GE099Q1FL0TU         NaN         NaN         NaN         NaN   

asin                   B00KKXCJQU  
reviewerID                         
A001114613O3F18Q5NVR6         NaN  
A00146182PNM90WNNAZ5Q         NaN  
A00165422B2GAUE3EL6Z0         NaN  
A00338282E99B8OR2JYTZ         NaN  
A00354001GE099Q1FL0TU         NaN  

[5 rows x 23033 columns]

In [16]:
user_item_mat.fillna(value=0)

asin                   0000031887  0123456479  1608299953  1617160377  \
reviewerID                                                              
A001114613O3F18Q5NVR6         0.0         0.0         0.0         0.0   
A00146182PNM90WNNAZ5Q         0.0         0.0         0.0         0.0   
A00165422B2GAUE3EL6Z0         0.0         0.0         0.0         0.0   
A00338282E99B8OR2JYTZ         0.0         0.0         0.0         0.0   
A00354001GE099Q1FL0TU         0.0         0.0         0.0         0.0   
A00404823GU1Q517KP4Z8         0.0         0.0         0.0         0.0   
A00475741WVLQL5CVWK2Z         0.0         0.0         0.0         0.0   
A0055084JB2YQW2IDOSQ          0.0         0.0         0.0         0.0   
A00635603LUUJQPQWSJW1         0.0         0.0         0.0         0.0   
A007227915NZZC7B6P030         0.0         0.0         0.0         0.0   
A0107229P6G90UKRJYQW          0.0         0.0         0.0         0.0   
A01103631SAT3BPLD52LV         0.0         0.0         0.0         0.0   
A01194842MEQEG9QC0W1M         0.0         0.0         0.0         0.0   
A0145698H8AAYMRXLBD8          0.0         0.0         0.0         0.0   
A0148968UM59JS3Y8D1M          0.0         0.0         0.0         0.0   
A015565634RZNSDLJBE5M         0.0         0.0         0.0         0.0   
A01749481KYG2RR0SF6GR         0.0         0.0         0.0         0.0   
A02155413BVL8D0G7X6DN         0.0         0.0         0.0         0.0   
A021943320Y3C5B58IY79         0.0         0.0         0.0         0.0   
A0224041E58B9YLYXLOL          0.0         0.0         0.0         0.0   
A022899328A0QROR32DCT         0.0         0.0         0.0         0.0   
A02324053VU4N09WNQTBN         0.0         0.0         0.0         0.0   
A02755422E9NI29TCQ5W3         0.0         0.0         0.0         0.0   
A03236882LUP4ARMDDMXU         0.0         0.0         0.0         0.0   
A034597326Z83X79S50FI         0.0         0.0         0.0         0.0   
A03523552G1P2GZGUZLQ9         0.0         0.0         0.0         0.0   
A036147939NFPC389VLK          0.0         0.0         0.0         0.0   
A03749271P4L9K1LN5UNT         0.0         0.0         0.0         0.0   
A03756272FRRX98COZNG7         0.0         0.0         0.0         0.0   
A04095881JK7GJRJYSY4N         0.0         0.0         0.0         0.0   
...                           ...         ...         ...         ...   
AZX4VFANLGB3V                 0.0         0.0         0.0         0.0   
AZXA1OKY8T4OQ                 0.0         0.0         0.0         0.0   
AZXEHGPNOO87I                 0.0         0.0         0.0         0.0   
AZXGPM8EKSHE9                 0.0         0.0         0.0         0.0   
AZXN5IJFD88G7                 0.0         0.0         0.0         0.0   
AZXP46IB63PU8                 0.0         0.0         0.0         0.0   
AZXPED8T2SVVF                 0.0         0.0         0.0         0.0   
AZXS6P5QWNMLC                 0.0         0.0         0.0         0.0   
AZXS8AO1H2JBI                 0.0         0.0         0.0         0.0   
AZXSXO5R20T6F                 0.0         0.0         0.0         0.0   
AZXUSHNU34EWX                 0.0         0.0         0.0         0.0   
AZY513DDDRN0Q                 0.0         0.0         0.0         0.0   
AZYAA6LINNWP8                 0.0         0.0         0.0         0.0   
AZYCDQF15WXET                 0.0         0.0         0.0         0.0   
AZYF2PH5JGEX8                 0.0         0.0         0.0         0.0   
AZYGUNBHBC9RI                 0.0         0.0         0.0         0.0   
AZYIPO42ISMQT                 0.0         0.0         0.0         0.0   
AZYJ4U46NUZBN                 0.0         0.0         0.0         0.0   
AZYP4FQ2L2C4O                 0.0         0.0         0.0         0.0   
AZYZQ7I9L7G3G                 0.0         0.0         0.0         0.0   
AZZ2HXC308RW1                 0.0         0.0         0.0         0.0   
AZZ9BV67BM0V0                 0.0         0.0         0.0 

In [24]:
#So now we have user-item matrix, we can start to work on User based colloborative filtering

test = np.array(user_item_mat)

In [25]:
test

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

In [27]:
from sklearn import *

C:\Users\GunjanPandya\Anaconda3\lib\site-packages\sklearn\lda.py:4: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)
C:\Users\GunjanPandya\Anaconda3\lib\site-packages\sklearn\qda.py:4: DeprecationWarning: qda.QDA has been moved to discriminant_analysis.QuadraticDiscriminantAnalysis in 0.17 and will be removed in 0.19.
  "in 0.17 and will be removed in 0.19.", DeprecationWarning)


In [30]:
nonan_test = np.nan_to_num(test)

In [31]:
nonan_test

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [33]:
user_sim_mat = metrics.pairwise.cosine_similarity(nonan_test)

In [36]:
user_sim_mat

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [59]:
def getUser(user_sim_mat,u):
    score=[]
    for others in range(len(user_sim_mat)):
        if others != u:
            score.append([user_sim_mat[u][others], others])
    score.sort()
    score.reverse()
    return score[:1]

In [60]:
getUser(user_sim_mat,0)

[[0.36031883586833519, 15]]

In [96]:
def standEstItem(nonan_test, u, user_sim_mat, item):
    n = np.shape(nonan_test)[1]
    simTotal = 0.0
    ratSimTotal = 0.0
    
    for j in range(n):
        userRating = nonan_test[u,j]
        if userRating == 0.0:
            continue
        
        sim = user_sim_mat[item][j]
        if sim<=0: sim = 0.0
            
        simTotal += 0
        ratSimTotal += sim * userRating
    
    if simTotal == 0:
        return 0
    else:
        return ratSimTotal/simTotal
        

In [105]:
def getItem(nonan_test, user_sim_mat, u):
    #unratedItems = np.nonzero(nonan_test[u])
    
    unratedItems = np.nonzero(np.matrix(nonan_test[u,:]).A == 0)[1]
    
    itemScores = []
    
    for item in unratedItems:
        estimatedScore = standEstItem(nonan_test, u, user_sim_mat, item)
        print(estimatedScore)
        itemScores.append((item,estimatedScore))
        
    return sorted(itemScores, key=lambda jj:jj[1], reverse=True)[:3]
    #for item in unratedItems:
    #    estimatedscore = 

In [ ]:
getItem(nonan_test, user_sim_mat, 0)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [ ]:
pwd